# Generated by Django 5.0.3 on 2024-10-21 20:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("AirWellApp", "0002_productreview"),
    ]

    operations = [
        migrations.CreateModel(
            name="YouTubeVideo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "video_url",
                    models.URLField(
                        help_text="Enter the YouTube embed URL, e.g., https://www.youtube.com/embed/VIDEO_ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
